title: PSMade - Blog de couture
permalink: /:title/

description: >
  Blog de couture où je partage mes réalisations homemade, des astuces techniques, mes bonnes adresses de tissu et les marques de patron qui m'inspirent.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ps-made.com" # the base hostname & protocol for your site, e.g. http://example.com
production_url: "http://ps-made.com"

# Build settings
markdown: kramdown
gems:
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "_posts"
    values:
      fav: false
