title: Perrine Self Made
permalink: /:title/

description: >
  De la couture
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
exclude:
  - Gemfile
  - Gemfile.lock
